version: '3'
services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  db:
    image: postgres:13.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
