version: "3"
services:
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    links:
      - db
    ports:
      - "3000:3000"
  db:
    image: postgres:13.9-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-dbs:/var/lib/postgresql/data
volumes:
  postgres-dbs: