import { Router } from 'express';
import { ValidateQueryParams } from '../common/middlewares/validate-query.middleware';
import { BasicQueryParams } from '../dto/basic-query-params.dto';
import { findAll, findById } from '../controllers/user.controller';
import Auth from '../common/middlewares/auth.middleware';
import { ValidRoles } from '../interfaces/valid_roles.interface';
import routeParamUUIDValidation from '../common/middlewares/route-param-uuid-validation.middleware';
const userRouter = Router();
userRouter.get('', Auth(ValidRoles.admin),ValidateQueryParams(BasicQueryParams), findAll);
userRouter.get('/:id', Auth(), routeParamUUIDValidation('id'), findById);
export default userRouter;